# Base image
FROM nginx:1.24
# Install dependencies
RUN apt update -qq && apt -y install apache2-utils

# Copy Nginx config template
COPY docker/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]
